### ISSUE TITLE
Marketing spots display strangely in Firefox

### ISSUE THREAD

**Issue by emmarichardson** [bmbrands/moodle-theme_elegance#105]
Marketing spots shift to right side and have unequal widths when displayed in Firefox.  With editing on, the extend outside of the box.  When browser is shrunk to imitate mobile mode, spots do not realign to fit screen.
Feature request - would it be possible to add options for changing the icon color for each marketing spots like with the Quick Links?

**Comment by bmbrands** [comment]
I have updated the marketing spots code and it allows the changing of icon colors. Please have a look!

**Comment by emmarichardson** [comment]
Much better - looks great!!  Slider now resizing as it should.

**Comment by bmbrands** [comment]
closing and fixed
