### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by emmarichardson** [bmbrands/moodle-theme_elegance#106]
Messages (and My Courses) link missing from navbar.  
Feature request - setting to allow Navbar to be fixed at top of page.

**Comment by bmbrands** [comment]
Fixed header option has been added too. Messages / My courses will follow soon

**Comment by bmbrands** [comment]
Changed the messages to an icon (mail envelope when a new mail is present). There was no my courses in Danny Wahl's version so skipping that for now
