### ISSUE TITLE
Column layout

### ISSUE THREAD

**Issue by emmarichardson** [bmbrands/moodle-theme_elegance#107]
The placement of the Add Block in the left column means that, if you are a right side block person, it always switched to three column layout with editing on.
Feature request - setting that allows selection of two or three column layout and an additional setting that allows for selection of left or right side for block placement.

**Comment by bmbrands** [comment]
I had to find a way of allowing admins to drag a block into that area when editing is on. Does not look great but I have not found a better way of doing this. Will keep this item open for now

**Comment by emmarichardson** [comment]
Could you at least put the Add Block block on the right to keep it consistent with previous right block layout?

**Comment by bmbrands** [comment]
Oh yes. I am going to add in a setting to configure the blocks :)
left + right
left only
right only

**Comment by emmarichardson** [comment]
: )

Emma Richardson
Distance Learning Coordinator
Direct: 719-650-3037



On October 20, 2015 at 8:47:54 AM, Bas Brands (notifications@github.com<mailto:notifications@github.com>) wrote:

Oh yes. I am going to add in a setting to configure the blocks :)
left + right
left only
right only

**Comment by bmbrands** [comment]
Ok added now
