### ISSUE TITLE
Scrolling in docked item

### ISSUE THREAD

**Issue by emmarichardson** [bmbrands/moodle-theme_elegance#114]
<img width="261" alt="screen shot 2015-10-21 at 11 14 02 am" src="https://cloud.githubusercontent.com/assets/2079129/10644257/e202eb64-77e4-11e5-87e3-1761cd8b5b1a.png">
When first loading a page and then clicking on a docked item (administration block in my case), the scrollbar does not appear and it will not scroll.  Closing it and opening it again resolves the issue.   This is somewhat inconsistent on when it happens but it has happened enough times for me to add it here!

**Comment by emmarichardson** [comment]
Just figured this out.  When it is first open, there is no need to scroll but when you expand the admin menu, the scroll bar should appear and allow you to scroll but it doesn't...so when you reopen the menu, the admin menu is already expanded and so the block then scrolls correctly.  It is not adjusting to the expanding of the admin menu.

**Comment by bmbrands** [comment]
I did notice the docked blocks don't look great so fixed that. On my system I can scroll when opening items. Is this any different from the clean theme?

**Comment by emmarichardson** [comment]
Docked blocks look better. Replicated issue in clean theme - so either something strange with my site or 2.9.2 bug.

**Comment by bmbrands** [comment]
okay closing since not related to this theme
