### ISSUE TITLE
Glyph icon font

### ISSUE THREAD

**Issue by emmarichardson** [bmbrands/moodle-theme_elegance#115]
<img width="194" alt="screen shot 2015-10-21 at 11 10 45 am" src="https://cloud.githubusercontent.com/assets/2079129/10644178/664bec00-77e4-11e5-9867-3a791b72f086.png">
When glyph icon font is checked, all icons in menus are lost..

**Comment by bmbrands** [comment]
Hmm I can't replicate this. I am considering removing this option. I think it does not really add anything that better than current icons.

**Comment by emmarichardson** [comment]
Must be something with my site.  Have turned it off and cannot get rid of the weird icons.

**Comment by bmbrands** [comment]
Removed the option from the theme
