### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by emmarichardson** [bmbrands/moodle-theme_elegance#116]
While the CSS for the font appears to be the same as in the old Elegance - it does not appear to be the same! It looks like it is meant to be Roboto family - perhaps that font needs to be added?
<img width="194" alt="screen shot 2015-10-21 at 1 06 40 pm" src="https://cloud.githubusercontent.com/assets/2079129/10647280/a55dadb0-77f4-11e5-9b56-b7ae4cdf87d5.png">
<img width="203" alt="screen shot 2015-10-21 at 1 06 55 pm" src="https://cloud.githubusercontent.com/assets/2079129/10647279/a5596afc-77f4-11e5-81c8-3bfecc91162a.png">

**Comment by bmbrands** [comment]
Yep. Forgot to include it in the less files. I did like the default font :)
