### ISSUE TITLE
Additional links in Navbar

### ISSUE THREAD

**Issue by emmarichardson** [bmbrands/moodle-theme_elegance#118]
Feature Request:  Is it possible to add a setting to add an option to align additional links to the right so that there is separation between them and the Moodle User/Messaging menus? Or maybe a vertical line separator?
Old Elegance
<img width="1440" alt="screen shot 2015-10-22 at 10 12 09 am" src="https://cloud.githubusercontent.com/assets/2079129/10670980/642a7876-78a5-11e5-92db-44da736e05c2.png">
New Elegance
<img width="548" alt="screen shot 2015-10-22 at 8 16 33 am" src="https://cloud.githubusercontent.com/assets/2079129/10670952/477fbcd6-78a5-11e5-8c91-ee8cb736fc43.png">

**Comment by bmbrands** [comment]
I think replacing the messages with an icon achieves the same result!

I have moved my branch here on github to the master branch now
