### ISSUE TITLE
Front Page Content Feature Request

### ISSUE THREAD

**Issue by emmarichardson** [bmbrands/moodle-theme_elegance#122]
Currently, the Front Page content shows below slideshow/marketing spots.  It also pulls the header background and site title.
It would be nice it we had the option to place it directly below the navbar in the header position.  Currently it seems to split the page.
<img width="1392" alt="screen shot 2015-10-27 at 8 59 00 am" src="https://cloud.githubusercontent.com/assets/2079129/10762166/80aaaf82-7c8a-11e5-9a9d-c0a688805a5c.png">

**Comment by bmbrands** [comment]
It is currently under the navbar with no styling
