### ISSUE TITLE
Front page content area does not align

### ISSUE THREAD

**Issue by emmarichardson** [bmbrands/moodle-theme_elegance#127]
Margins are slightly off on the front page content area.  Margins left and right of -15px seem to fix it to where it then lines up with marketing spots container.  Image shows how it does not match up with marketing spots container or navbar. (I also moved it up to look like a header so that is why it is right next to navbar - ignore that part!)
<img width="1399" alt="screen shot 2015-10-29 at 2 23 37 pm" src="https://cloud.githubusercontent.com/assets/2079129/10831032/aba5ac9a-7e48-11e5-8d53-84ffebdd96c2.png">

**Comment by bmbrands** [comment]
has been fixed a while ago I think. Could you test it on your end?

**Comment by emmarichardson** [comment]
Fixed - thanks!
