### ISSUE TITLE
Your first 3.0 challenge!  Docked blocks...

### ISSUE THREAD

**Issue by emmarichardson** [bmbrands/moodle-theme_elegance#128]
Docked blocks are behaving strangely in Chrome in 3.0.  This is very noticeable in the admin block.  When you expand the menu,instead of the top of the block staying level with the top of the tab in the dock, it extends up towards the top of the page.  This then becomes an issue with the fixed navbar as the top of the dock will hide behind it.  (in firefox, the navbar sits behind the docked block so not a problem)
Two images show how it is on 2.9.2 and how it is on 3.0.
<img width="484" alt="screen shot 2015-10-29 at 2 31 44 pm" src="https://cloud.githubusercontent.com/assets/2079129/10831192/e4c35d82-7e49-11e5-8cfe-c0641377d785.png">
<img width="259" alt="screen shot 2015-10-29 at 2 31 53 pm" src="https://cloud.githubusercontent.com/assets/2079129/10831193/e4c80eb8-7e49-11e5-84b2-caea15197826.png">

On a side note, I think the docked blocks look much better with the min-width is set to 250px or 300px instead of 200px.  In 3.0, the Clean docked blocks are pretty wide.
I replicated this issue in Bootstrap too. (At least the expanding upwards part of it)

**Comment by gjb2048** [comment]
MDL-51229

**Comment by bmbrands** [comment]
should be ok now!
