### ISSUE TITLE
Marketing spots in two per row display differently

### ISSUE THREAD

**Issue by emmarichardson** [bmbrands/moodle-theme_elegance#132]
If you select to display two marketing spots per row, the rows display differently - first row does not use same padding(?) as second row.
<img width="1415" alt="screen shot 2015-10-31 at 7 31 34 am" src="https://cloud.githubusercontent.com/assets/2079129/10863925/bdc7cebc-7fa1-11e5-8e2b-fcb96e7550ee.png">

**Comment by gjb2048** [comment]
I think the first row looks better :)

**Comment by emmarichardson** [comment]
I think somewhere between the two would be best - the first row isn't centered vertically - (that would drive my ocd side crazy!) but the second row has a little too much white space..

**Comment by mruasar** [comment]
I couldn't replicate this, mine all comes equal. 
tested on Win 7 in FF, Chrome, Opera (Latest) and IE 11 on Moodle 3

**Comment by emmarichardson** [comment]
I now cannot replicate either...closing this one out...
