### ISSUE TITLE
Groups page layout

### ISSUE THREAD

**Issue by emmarichardson** [bmbrands/moodle-theme_elegance#134]
On the groups page in a course (both 2.9 and 3.0), the layout only uses one column instead of two like Clean.  Screenshots attached.
<img width="853" alt="screen shot 2015-11-03 at 2 12 30 pm" src="https://cloud.githubusercontent.com/assets/2079129/10921911/765b2402-8235-11e5-8d41-82f2b9fb6b3b.png">
<img width="597" alt="screen shot 2015-11-03 at 2 14 46 pm" src="https://cloud.githubusercontent.com/assets/2079129/10921912/7663a6ae-8235-11e5-85e4-8ca1b4ae4ea2.png">

**Comment by bmbrands** [comment]
Well spotted. This is actually a theme bootstrap issue. I fixed it in theme bootstrap so please update that to see this fixed.
