### ISSUE TITLE
Removal of <hr> from footer

### ISSUE THREAD

**Issue by mruasar** [bmbrands/moodle-theme_elegance#135]
In previous Elegance, there was a small hint of <hr> between footnote content and copyright, where copyright information is removed from new elegance, horizontal rule still remains there and appears just above the foot note content. 

![hbar-elegance](https://cloud.githubusercontent.com/assets/5184754/10925360/38a25598-82af-11e5-8dc8-3c52d1e60304.png)

**Comment by bmbrands** [comment]
Has been removed!
