### ISSUE TITLE
Background extended beyond footer area

### ISSUE THREAD

**Issue by mruasar** [bmbrands/moodle-theme_elegance#136]
As shown in picture, unless footer content extending beyong 130 pixels height is used, the background shows extended beyond footer area. 
can be just extend footer area (even blank) to reach the bottom - like it was in previous elegance.
![bg-extend](https://cloud.githubusercontent.com/assets/5184754/10925465/33d55794-82b0-11e5-995f-d1091848679a.png)

**Comment by bmbrands** [comment]
I have rewritten the footer css so this should be fixed now. Since the footer is fixed to the bottom of the page I hope my fixes will work for most browsers / custom footer content. Fingers crossed
