### ISSUE TITLE
Top Navigation Hover - not issue but enhancement 

### ISSUE THREAD

**Issue by mruasar** [bmbrands/moodle-theme_elegance#137]
In previous elegance hovering mouse over top navigation (links) reveal theme color under it, looked cool, and that is missing in current - As mentioned in subject, not a requirement but will look better if its there. 
you can see practical example of that on www.trainmyteacher.com 
![elegance-hover](https://cloud.githubusercontent.com/assets/5184754/10925548/f86e56dc-82b0-11e5-8acf-73405fcdd863.png)

**Comment by bmbrands** [comment]
This was still on my to-do list.

I rewrote the less files to generate a similar style navbar for both the navbar-default and navbar-inverse settings (see theme general settings).
