### ISSUE TITLE
CSS Style - Quick Link Button color 11

### ISSUE THREAD

**Issue by sbardt** [bmbrands/moodle-theme_elegance#140]
There is a bug in the following stylesheet:

less/elements/quicklinks.less

There is no value association for quicklinkbuttoncolor11!

This is the section:
.quicklinkbuttoncolor1 {
    background: @quicklinkbuttoncolor11;
}
... and it should read:
.quicklinkbuttoncolor11 {
    background: @quicklinkbuttoncolor11;
}

**Comment by bmbrands** [comment]
Thanks for reporting this! Fixed now
