### ISSUE TITLE
In My Moodle course photos dissapeared

### ISSUE THREAD

**Issue by matijakovac** [bmbrands/moodle-theme_elegance#161]
Hi,
I just updated our Moodle to 3.x and updated theme Elegance too.
I noticed many changes, but I can't figure out why the course description photo is missing from the 'My Moodle' page that users see upon login.
Also, the login screen looks completely different than before.
Thanks for help!

**Comment by bmbrands** [comment]
Hi,
Could you include a screenshot so I can see what it looks like?

**Comment by matijakovac** [comment]
Hi,
I can't seem to figure out if it is intentional or just my error, but the block that displays tiles with courses ('My Courses') is gone.
Please see a screenshot from the original release of Elegance bellow.
![dashboard](https://cloud.githubusercontent.com/assets/19140107/14950499/5371fdb6-1052-11e6-808c-d19ec4ddc994.jpg)

All I see now is 'course overview'.
Thank you.

**Comment by matijakovac** [comment]
Hi Bas,
any help on this one would be much appreciated.
Thank you,

**Comment by bmbrands** [comment]
I am sorry but the my courses section with tiles is no longer part of this theme. It was stripped because it does not really belong in a theme. It should be a separate Moodle block type plugin.
Creating a block that generates this listing is quite simple

**Comment by matijakovac** [comment]
Hi Bas, thanks for your feedback. I was afraid you might say that.
Could you please point me in the right direction or is there a chance to use the code used in the previous versions?
Thanks

**Comment by bmbrands** [comment]
It would need some work but the original code is here:

(function mycourses ) 
https://github.com/eduridden/moodle-theme_elegance/blob/master/renderers/core_renderer.php#L512
