### ISSUE TITLE
Pull down menu not aviable

### ISSUE THREAD

**Issue by mentingm** [bmbrands/moodle-theme_elegance#162]
The problem is that the Pull Down menu on the right Top is not aviable. When i click on the pull down menu (my Name) then nothing happend. What can be the problem. It accured at Firefox and IE.
![image](https://cloud.githubusercontent.com/assets/19487018/15421649/bf66033e-1e74-11e6-8e9b-1845fc7e59c6.png)

**Comment by bmbrands** [comment]
Thanks. Could you post a screenshot of the JavaScript console instead. It should look something like this:

![screen shot 2016-05-20 at 10 29 35](https://cloud.githubusercontent.com/assets/491790/15421867/d9876c0c-1e75-11e6-9bda-c87da6370af4.png)

**Comment by mentingm** [comment]
![image](https://cloud.githubusercontent.com/assets/19487018/15422680/f95fcb60-1e79-11e6-8914-0e0d43e32706.png)
I get an error on the theme bootstrap. I installed it again but the error remains.

**Comment by bmbrands** [comment]
Okay. What version of the bootstrap theme are you using?

**Comment by mentingm** [comment]
I installed Bootstrap_moodle30_2016042200

**Comment by bmbrands** [comment]
That is the correct version. 

Can you check if the file /theme/bootstrap/amd/src/bootstrap.js is present and starts with:

```
/* jshint ignore:start */
define(['jquery', 'core/log'], function($, log) {
```

**Comment by mentingm** [comment]
Yes, the file en the Program line is present.

**Comment by bmbrands** [comment]
Can you switch to the bootstrap theme ? Is it fully functional?

**Comment by mentingm** [comment]
I switched to the normal bootstrap and this isn'fully functional. I have the same issue. :(

**Comment by bmbrands** [comment]
Have you installed any other plugin in your install?

**Comment by mentingm** [comment]
Thanx for you reply! I found the issue. I removed another Theme plugin that i installed and not using. I even installed Bootstrap again and problem solved.

**Comment by bmbrands** [comment]
Okay, I am glad it is solved! Closing the issue.
