### ISSUE TITLE
Change height of the footer.

### ISSUE THREAD

**Issue by mentingm** [bmbrands/moodle-theme_elegance#163]
How can i change the height of the footer. I changed the Custom.css but nothing occures.

**Comment by learningtechnologyservices** [comment]
The Custom CSS box in the theme settings page should be used when adding custom css to the theme. If it does not work when adding it there please copy-paste your CSS here so I can have a look

**Comment by bmbrands** [comment]
The Custom CSS box in the theme settings page should be used when adding custom css to the theme. If it does not work when adding it there please copy-paste your CSS here so I can have a look

**Comment by mentingm** [comment]
My custom.css look like this:
/* @end */

[[setting:customcss]]
#page-footer {height: 15px; }

I did also clear the cache of the website.

**Comment by bmbrands** [comment]
Ah ok. The footer for theme elegance is a little bit more complex than that. There is quite a lot of CSS for that. To change it it would be better to change the Less file variables. See:
https://github.com/bmbrands/moodle-theme_elegance/blob/master/less/variables.less#L26

These less files recompile into CSS when you purge Moodle caches.
