### ISSUE TITLE
theme_elegance | enablecustomlogin is not functional

### ISSUE THREAD

**Issue by mentingm** [bmbrands/moodle-theme_elegance#166]
I have update the Moodle site to  in Moodle 3.0.3 (Build: 20160314). It is know not possible to use the nice custom inlogscreen. Is it possible to use it again?

**Comment by bmbrands** [comment]
The login screen that used to be in this theme was sort of hacky and not very well written. I will not implement that feature again. The is a feature to insert your own background pictures for the login page... Hopefully using that you could get some nice results too.
