### ISSUE TITLE
Theme 3.0 on Moodle 3.1 - Grader

### ISSUE THREAD

**Issue by LucasFonseca-ISPED** [bmbrands/moodle-theme_elegance#167]
I installed the latest version of Moodle and now the Grader page like "<moodle>/mod/assign/view.php?id=<NUMBER>&action=grader" shows everything out of layout. Tried other themes from moodle.org and worked well. SS attached. 
If I crop the browser window to width on 771, shows everything. (SS nº2).

On Moodle 3.0 didn't had this issue. 

![ss1_eleganceissue](https://cloud.githubusercontent.com/assets/20360437/16696790/ec3dd052-451c-11e6-9b0e-c691d96be68c.JPG)
![ss2_eleganceissue](https://cloud.githubusercontent.com/assets/20360437/16696791/ec40d1d0-451c-11e6-8a2c-c41a97b0903a.jpg)

**Comment by levleontiev** [comment]
Having the same problem on Moodle 3.1 under Safari browser @ Mac os. 
Please advise

**Comment by bmbrands** [comment]
fixed in latest release
