### ISSUE TITLE
3.1 missing fontawesome

### ISSUE THREAD

**Issue by M4G1** [bmbrands/moodle-theme_elegance#170]
I´ve noticed a possible bug in the 3.1 version. The font fontawesome (ttf/woff/woff2) is not is not displayed and I get a 404. The URL to the font is: https://10.0.1.50/theme/font.php?theme=elegance&component=theme&font=fontawesome-webfont.woff2?v=4.4.0. If I change it to https://10.0.1.50/theme/font.php?theme=elegance&component=theme&font=fontawesome-webfont.woff2&v=4.4.0 (?-->&) the font is accessible. Is this some kind of bug in the theme or a misconfiguration of my system (Turnkey appliance)?

**Comment by scara** [comment]
Hi @M4G1,
are you sure you're running the latest version of the code?
Look at #153 and, for the complete story, https://moodle.org/mod/forum/discuss.php?d=325511.

HTH,
Matteo

**Comment by M4G1** [comment]
Hi Matteo,

thank you for your quick response. I´ve just installed the newest version of the theme from the repository (2016080100) and it is still the same:

![bildschirmfoto 2016-08-11 um 11 08 28](https://cloud.githubusercontent.com/assets/18679876/17583930/ff21c24e-5fb3-11e6-9831-e0e334409105.png)

![bildschirmfoto 2016-08-11 um 11 09 18](https://cloud.githubusercontent.com/assets/18679876/17583953/1be02d80-5fb4-11e6-8b05-a2d5c5c78675.png)

Is there something I need to adjust in the system (.htaccess / apache2.conf). I am currently not using htaccess and my apache2.conf is the default one. 

I am using the Moodle Turnkey appliance. 

Thanks,
Matthias

**Comment by scara** [comment]
Hi @M4G1,
with "repository" do you mean here, github, or the Moodle Plug-ins?
As a workaround you should enable the so called "Slash arguments", _Administration > Site administration > Server > HTTP_ (https://docs.moodle.org/31/en/Using_slash_arguments), hoping that the appliance is properly configured to support it (never used).

HTH,
Matteo

**Comment by M4G1** [comment]
Hi Matteo,

I mean the Github repository. Slash arguments is turned on by default in Moodle 3.1. What about the the argument itself at the end of the URL (?v=4.4.0). Why can I access the font if I change it to &v=4.4.0?

Thanks,
Matthias

**Comment by scara** [comment]
Good point (if it has been installed from scratch and not coming from un update)!
I was in a hurry: did you already double check its configured value via http://hostname/path/to/admin/settings.php?section=http ?

If yes, in the next days I'll review the original PR to see why it looks like not compatible with Moodle 3.1: AFAIK `$CFG->slasharguments` is still there and you can change its value.

BTW, you can access the font when changing the URL since you're fixing the URL syntax by your own (https://moodle.org/mod/forum/discuss.php?d=325511#p1308296).

HTH,
Matteo

**Comment by M4G1** [comment]
Are we talking about the settings.php in var/www/moodle/admin/? If so, thats how it looks like:

<?php

require_once('../config.php');
require_once($CFG->libdir.'/adminlib.php');

$section = required_param('section', PARAM_SAFEDIR);
$return = optional_param('return','', PARAM_ALPHA);
$adminediting = optional_param('adminedit', -1, PARAM_BOOL);

/// no guest autologin
require_login(0, false);
$PAGE->set_context(context_system::instance());
$PAGE->set_url('/admin/settings.php', array('section' => $section));
$PAGE->set_pagetype('admin-setting-' . $section);
$PAGE->set_pagelayout('admin');
$PAGE->navigation->clear_cache();
navigation_node::require_admin_tree();

$adminroot = admin_get_root(); // need all settings
$settingspage = $adminroot->locate($section, true);

if (empty($settingspage) or !($settingspage instanceof admin_settingpage)) {
    if (moodle_needs_upgrading()) {
        redirect(new moodle_url('/admin/index.php'));
    } else {
        print_error('sectionerror', 'admin', "$CFG->wwwroot/$CFG->admin/");
    }
    die;
}

if (!($settingspage->check_access())) {
    print_error('accessdenied', 'admin');
    die;
}

/// WRITING SUBMITTED DATA (IF ANY) -------------------------------------------------------------------------------

$statusmsg = '';
$errormsg  = '';

if ($data = data_submitted() and confirm_sesskey()) {
    if (admin_write_settings($data)) {
        redirect($PAGE->url, get_string('changessaved'), null, \core\output\notification::NOTIFY_SUCCESS);
    }

    if (empty($adminroot->errors)) {
        switch ($return) {
            case 'site': redirect("$CFG->wwwroot/");
            case 'admin': redirect("$CFG->wwwroot/$CFG->admin/");
        }
        redirect($PAGE->url);
    } else {
        $errormsg = get_string('errorwithsettings', 'admin');
        $firsterror = reset($adminroot->errors);
    }
    $settingspage = $adminroot->locate($section, true);
}

if ($PAGE->user_allowed_editing() && $adminediting != -1) {
    $USER->editing = $adminediting;
}

/// print header stuff ------------------------------------------------------------
if (empty($SITE->fullname)) {
    $PAGE->set_title($settingspage->visiblename);
    $PAGE->set_heading($settingspage->visiblename);

    echo $OUTPUT->header();
    echo $OUTPUT->box(get_string('configintrosite', 'admin'));

    if ($errormsg !== '') {
        echo $OUTPUT->notification($errormsg);

    } else if ($statusmsg !== '') {
        echo $OUTPUT->notification($statusmsg, 'notifysuccess');
    }

    // ---------------------------------------------------------------------------------------------------------------

    echo '<form action="' . $PAGE->url . '" method="post" id="adminsettings">';
    echo '<div class="settingsform clearfix">';
    echo html_writer::input_hidden_params($PAGE->url);
    echo '<input type="hidden" name="sesskey" value="'.sesskey().'" />';
    echo '<input type="hidden" name="return" value="'.$return.'" />';
    // HACK to prevent browsers from automatically inserting the user's password into the wrong fields.
    echo prevent_form_autofill_password();

    echo $settingspage->output_html();

    echo '<div class="form-buttons"><input class="form-submit" type="submit" value="'.get_string('savechanges','admin').'" /></div>';

    echo '</div>';
    echo '</form>';

} else {
    if ($PAGE->user_allowed_editing()) {
        $url = clone($PAGE->url);
        if ($PAGE->user_is_editing()) {
            $caption = get_string('blockseditoff');
            $url->param('adminedit', 'off');
        } else {
            $caption = get_string('blocksediton');
            $url->param('adminedit', 'on');
        }
        $buttons = $OUTPUT->single_button($url, $caption, 'get');
        $PAGE->set_button($buttons);
    }

    $visiblepathtosection = array_reverse($settingspage->visiblepath);

    $PAGE->set_title("$SITE->shortname: " . implode(": ",$visiblepathtosection));
    $PAGE->set_heading($SITE->fullname);
    echo $OUTPUT->header();

    if ($errormsg !== '') {
        echo $OUTPUT->notification($errormsg);

    } else if ($statusmsg !== '') {
        echo $OUTPUT->notification($statusmsg, 'notifysuccess');
    }

    // ---------------------------------------------------------------------------------------------------------------

    echo '<form action="' . $PAGE->url . '" method="post" id="adminsettings">';
    echo '<div class="settingsform clearfix">';
    echo html_writer::input_hidden_params($PAGE->url);
    echo '<input type="hidden" name="sesskey" value="'.sesskey().'" />';
    echo '<input type="hidden" name="return" value="'.$return.'" />';
    // HACK to prevent browsers from automatically inserting the user's password into the wrong fields.
    echo prevent_form_autofill_password();
    echo $OUTPUT->heading($settingspage->visiblename);

    echo $settingspage->output_html();

    if ($settingspage->show_save()) {
        echo '<div class="form-buttons"><input class="form-submit" type="submit" value="'.get_string('savechanges','admin').'" /></div>';
    }

    echo '</div>';
    echo '</form>';
}

$PAGE->requires->yui_module('moodle-core-formchangechecker',
        'M.core_formchangechecker.init',
        array(array(
            'formid' => 'adminsettings'
        ))
);
$PAGE->requires->string_for_js('changesmadereallygoaway', 'moodle');

echo $OUTPUT->footer();

Thanks,
Matthias

**Comment by scara** [comment]
Not exactly, apologies for not being clear enough: you need to open it with your browser.
If your Moodle instance is available at e.g. http://example.org/moodle you need to open the HTTP configuration settings by means of your browser pointing to http://example.org/moodle/admin/settings.php?section=http .

HTH,
Matteo

**Comment by M4G1** [comment]
Sorry Matteo, I got it now. These are the HTTP settings: 

![bildschirmfoto 2016-08-11 um 14 18 36](https://cloud.githubusercontent.com/assets/18679876/17588359/95b4606c-5fce-11e6-8115-69aae3c3b5e4.png)

Thanks,
Matthias

**Comment by scara** [comment]
Hi @M4G1,
I'll try by myself in a 3.1 MDL env: at the moment, I cannot understand why your instance should deliver not-slash-arguments-friendly URLs, e.g.: https://10.0.1.50/theme/font.php?theme=elegance&component=theme&font=fontawesome-webfont.woff2?v=4.4.0, when _slash arguments_ is checked. As a consequence of such unexpected behavior, `?v04.4.0` is there w/o `&` since `$CFG->slasharguments` is `true`.

HTH,
Matteo

**Comment by M4G1** [comment]
Thank you very much for looking into this matter. I am looking forward to your reply.

**Comment by M4G1** [comment]
Hi Matteo,

I´ve just reinstalled the appliance and an updated version of Moodle and now everything is working fine. Thank you for your quick responses and the effort.

All the best,
Matthias

**Comment by scara** [comment]
Thanks for the update!
You're welcome :smile:.
