### ISSUE TITLE
Course (edit) - drag & drop icon misaligned

### ISSUE THREAD

**Issue by M4G1** [bmbrands/moodle-theme_elegance#171]
It is not possible to arrange course activities, because the drag and drop element is misaligned/overlapping. This applies only to the Elegance Theme.

Elegance: 
![bildschirmfoto 2016-08-12 um 13 26 37](https://cloud.githubusercontent.com/assets/18679876/17621085/4a727120-6091-11e6-8b28-0de168f212fb.png)

Clean:
![bildschirmfoto 2016-08-12 um 13 36 22](https://cloud.githubusercontent.com/assets/18679876/17621162/cccb49e4-6091-11e6-8e74-387c8cf1a0c9.png)

**Comment by bmbrands** [comment]
Thanks for reporting this. I have fixed the issue and released a new version on moodle.org and here on Github.

**Comment by M4G1** [comment]
Confirmed. Thank you!
