### ISSUE TITLE
Showing blank Home page after updating to v4.0.0  on Moodle 3.6

### ISSUE THREAD

**Issue by nimit2006** [bmbrands/moodle-theme_elegance#182]
After Installing theme My moodle home page showing following error.

Fatal error: Declaration of theme_elegance\output\carousel::export_for_template($output) must be compatible with templatable::export_for_template(renderer_base $output) in /home/username/public_html/moodle/theme/elegance/classes/output/carousel.php on line 37

please tell me how to fix it. I updated Moodle 3.6 and using theme 4.0

**Comment by bmbrands** [comment]
Hi @nimit2006. I have found and fixed the issue.
